find_package(Qt6 6.11 REQUIRED COMPONENTS Widgets Concurrent)
set(FEQ_QT_LICENSE_DIR "" CACHE PATH "Prepared Qt notices and complete matching sources")
set(FEQ_APPLICATION_RESOURCES "${CMAKE_CURRENT_BINARY_DIR}/share/feq")
file(MAKE_DIRECTORY "${FEQ_APPLICATION_RESOURCES}/examples/test" "${FEQ_APPLICATION_RESOURCES}/manuals" "${FEQ_APPLICATION_RESOURCES}/licenses")
file(COPY "${CMAKE_CURRENT_SOURCE_DIR}/originals/feq1061/wrdapp/FEQ_10.61/DATA/"
    DESTINATION "${FEQ_APPLICATION_RESOURCES}/examples/data")
configure_file(originals/manuals/feq.pdf "${FEQ_APPLICATION_RESOURCES}/manuals/feq.pdf" COPYONLY)
configure_file(originals/manuals/fequtl.pdf "${FEQ_APPLICATION_RESOURCES}/manuals/fequtl.pdf" COPYONLY)
configure_file(LICENSE "${FEQ_APPLICATION_RESOURCES}/licenses/LICENSE" COPYONLY)
configure_file(NOTICE.md "${FEQ_APPLICATION_RESOURCES}/licenses/NOTICE.md" COPYONLY)
configure_file(engines/runtime/NOTICE.txt "${FEQ_APPLICATION_RESOURCES}/licenses/Netlib.txt" COPYONLY)

configure_file(app/packaging/START-HERE.txt "${FEQ_APPLICATION_RESOURCES}/START-HERE.txt" COPYONLY)
configure_file(app/packaging/feq-workbench.svg "${FEQ_APPLICATION_RESOURCES}/feq-workbench.svg" COPYONLY)
if(FEQ_QT_LICENSE_DIR)
    if(NOT EXISTS "${FEQ_QT_LICENSE_DIR}/sources.json")
        message(FATAL_ERROR "Prepare the Qt source and notice bundle with tools/prepare_qt_bundle.py first.")
    endif()
    file(COPY "${FEQ_QT_LICENSE_DIR}/" DESTINATION "${FEQ_APPLICATION_RESOURCES}/licenses/qt")
else()
    install(CODE "message(FATAL_ERROR \"Set FEQ_QT_LICENSE_DIR to the bundle created by tools/prepare_qt_bundle.py before redistributing the desktop.\")")
endif()

add_library(feq_desktop_support STATIC app/project_runner.cpp app/main_window.cpp)
target_link_libraries(feq_desktop_support PUBLIC Qt6::Widgets Qt6::Concurrent)
target_compile_features(feq_desktop_support PUBLIC cxx_std_20)
set_target_properties(feq_desktop_support PROPERTIES CXX_EXTENSIONS OFF)
target_compile_definitions(feq_desktop_support PRIVATE "FEQ_APPLICATION_RESOURCES=\"${FEQ_APPLICATION_RESOURCES}\"")
if(MSVC)
    target_compile_options(feq_desktop_support PUBLIC /utf-8)
endif()
feq_checks(feq_desktop_support)

qt_add_executable(feq-workbench WIN32 MACOSX_BUNDLE app/main.cpp app/verify_installation.cpp)
target_link_libraries(feq-workbench PRIVATE feq_desktop_support)
if(APPLE)
    target_sources(feq-workbench PRIVATE app/packaging/feq-workbench.icns)
    set_source_files_properties(app/packaging/feq-workbench.icns PROPERTIES MACOSX_PACKAGE_LOCATION Resources)
    set_target_properties(feq-workbench PROPERTIES MACOSX_BUNDLE_ICON_FILE "feq-workbench.icns")
elseif(WIN32)
    target_link_options(feq-workbench PRIVATE "/MANIFEST:EMBED" "/MANIFESTINPUT:${CMAKE_CURRENT_SOURCE_DIR}/engines/support/windows.manifest")
    enable_language(RC)
    set(FEQ_ICON_ICO "${CMAKE_CURRENT_SOURCE_DIR}/app/packaging/feq-workbench.ico")
    configure_file(app/packaging/windows-icon.rc.in "${CMAKE_CURRENT_BINARY_DIR}/windows-icon.rc" @ONLY)
    target_sources(feq-workbench PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/windows-icon.rc")
endif()
set_target_properties(feq-workbench PROPERTIES
    MACOSX_BUNDLE_BUNDLE_NAME "FEQ Workbench"
    MACOSX_BUNDLE_GUI_IDENTIFIER "org.rainstar.feq-workbench"
    MACOSX_BUNDLE_BUNDLE_VERSION "${PROJECT_VERSION}"
    MACOSX_BUNDLE_SHORT_VERSION_STRING "${PROJECT_VERSION}")
if(UNIX AND NOT APPLE)
    set_target_properties(feq-workbench PROPERTIES INSTALL_RPATH "$ORIGIN/../${CMAKE_INSTALL_LIBDIR}")
endif()
if(APPLE)
    set_target_properties(feq-workbench PROPERTIES OUTPUT_NAME "FEQ Workbench")
endif()
add_dependencies(feq-workbench feq fequtl)
feq_checks(feq-workbench)
if(APPLE)
    add_custom_command(TARGET feq-workbench POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:feq> $<TARGET_FILE_DIR:feq-workbench>/feq
        COMMAND ${CMAKE_COMMAND} -E copy_if_different $<TARGET_FILE:fequtl> $<TARGET_FILE_DIR:feq-workbench>/fequtl
        COMMAND ${CMAKE_COMMAND} -E copy_directory "${FEQ_APPLICATION_RESOURCES}" $<TARGET_FILE_DIR:feq-workbench>/../Resources)
endif()
install(TARGETS feq-workbench BUNDLE DESTINATION . RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR})
if(NOT APPLE)
    install(DIRECTORY "${FEQ_APPLICATION_RESOURCES}/" DESTINATION ${CMAKE_INSTALL_DATADIR}/feq)
endif()
# Linux system libraries are installed by the distribution package manager.
# Bundle Qt; retain the distro's supported libc, X11 and graphics libraries.
set(feq_deploy_exclusions)
if(UNIX AND NOT APPLE)
    list(APPEND feq_deploy_exclusions POST_EXCLUDE_REGEXES "^/lib/" "^/usr/lib/")
endif()
qt_generate_deploy_app_script(TARGET feq-workbench OUTPUT_SCRIPT feq_desktop_deploy
    NO_TRANSLATIONS ${feq_deploy_exclusions})
install(SCRIPT ${feq_desktop_deploy})

if(BUILD_TESTING)
    find_package(Python3 COMPONENTS Interpreter REQUIRED)
    add_executable(feq_desktop_fake_engine tests/desktop_fake_engine.cpp)
    target_compile_features(feq_desktop_fake_engine PRIVATE cxx_std_20)
    feq_checks(feq_desktop_fake_engine)
    add_executable(feq_desktop_workflow_test tests/desktop_workflow_test.cpp)
    target_link_libraries(feq_desktop_workflow_test PRIVATE feq_desktop_support)
    feq_checks(feq_desktop_workflow_test)
    add_dependencies(feq_desktop_workflow_test feq fequtl feq_desktop_fake_engine)
    add_test(NAME desktop_workflow COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/check_desktop_workflow.py
        --runner $<TARGET_FILE:feq_desktop_workflow_test> --fake $<TARGET_FILE:feq_desktop_fake_engine>
        --resources "${FEQ_APPLICATION_RESOURCES}" --output "${CMAKE_CURRENT_BINARY_DIR}/desktop-verification")
    set_tests_properties(desktop_workflow PROPERTIES TIMEOUT 300 ENVIRONMENT "QT_QPA_PLATFORM=offscreen")
endif()

install(FILES app/packaging/START-HERE.txt DESTINATION .)
if(WIN32)
    install(PROGRAMS app/packaging/Start-FEQ.cmd DESTINATION .)
elseif(NOT APPLE)
    install(PROGRAMS app/packaging/Start-FEQ.sh DESTINATION .)
    install(FILES app/packaging/feq-workbench.desktop DESTINATION share/applications)
    install(FILES app/packaging/feq-workbench.svg DESTINATION share/icons/hicolor/scalable/apps)
endif()

set(CPACK_PACKAGE_NAME "FEQ-Workbench")
set(CPACK_PACKAGE_VENDOR "Rainstar")
set(CPACK_PACKAGE_CONTACT "https://github.com/falseywinchnet/legacy/issues")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "FEQ 10.61 and FEQUTL 5.80 native desktop applications")
set(CPACK_PACKAGE_VERSION "${PROJECT_VERSION}")
set(CPACK_PACKAGE_FILE_NAME "FEQ-Workbench-${PROJECT_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "FEQ Workbench")
if(WIN32)
    set(CPACK_GENERATOR "ZIP;NSIS")
    set(CPACK_NSIS_DISPLAY_NAME "FEQ Workbench")
    set(CPACK_NSIS_PACKAGE_NAME "FEQ Workbench")
    set(CPACK_NSIS_MODIFY_PATH OFF)
    set(CPACK_PACKAGE_EXECUTABLES "feq-workbench" "FEQ Workbench")
    set(CPACK_CREATE_DESKTOP_LINKS "feq-workbench")
elseif(APPLE)
    set(CPACK_GENERATOR "DragNDrop")
    set(CPACK_DMG_VOLUME_NAME "FEQ Workbench")
    set(CPACK_DMG_SLA_USE_RESOURCE_FILE_LICENSE OFF)
else()
    set(CPACK_GENERATOR "TGZ;DEB")
    set(CPACK_PROJECT_CONFIG_FILE "${CMAKE_CURRENT_SOURCE_DIR}/cmake/package-platform.cmake")
    set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/app/packaging/debian/postinst;${CMAKE_CURRENT_SOURCE_DIR}/app/packaging/debian/prerm")
    set(CPACK_DEBIAN_PACKAGE_CONTROL_STRICT_PERMISSION TRUE)
    set(CPACK_DEBIAN_PACKAGE_NAME "feq-workbench")
    set(CPACK_DEBIAN_PACKAGE_MAINTAINER "Rainstar")
    set(CPACK_DEBIAN_PACKAGE_DEPENDS "libc6 (>= 2.39), libstdc++6, libgcc-s1, libgl1, libegl1, libopengl0, libx11-6, libx11-xcb1, libxcb1, libxcb-cursor0, libxcb-icccm4, libxcb-image0, libxcb-keysyms1, libxcb-randr0, libxcb-render-util0, libxcb-shape0, libxcb-shm0, libxcb-sync1, libxcb-xfixes0, libxcb-xkb1, libxkbcommon0, libxkbcommon-x11-0, libfontconfig1, libfreetype6, libdbus-1-3, libsm6, libice6, libglib2.0-0t64")
endif()
include(CPack)

add_executable(feq_icon_export EXCLUDE_FROM_ALL tools/build_desktop_icons.cpp)
target_link_libraries(feq_icon_export PRIVATE Qt6::Widgets)
target_compile_features(feq_icon_export PRIVATE cxx_std_20)
feq_checks(feq_icon_export)
