set(FEQ_FEQ_SOURCES
    engines/feq/binsearch.cpp
    engines/feq/block.cpp
    engines/feq/brnmat.cpp
    engines/feq/chkinput.cpp
    engines/feq/common.cpp
    engines/feq/debug.cpp
    engines/feq/dmpmc.cpp
    engines/feq/doeqz.cpp
    engines/feq/dtendlay.cpp
    engines/feq/dual_source.cpp
    engines/feq/dynamic_storage.cpp
    engines/feq/exnmat.cpp
    engines/feq/feq.cpp
    engines/feq/fqshrarg.cpp
    engines/feq/fqshrftb.cpp
    engines/feq/fqshrinl.cpp
    engines/feq/fqshrlin.cpp
    engines/feq/fqshrplg.cpp
    engines/feq/fqshrstr.cpp
    engines/feq/fqshrtdl.cpp
    engines/feq/fqshrtim.cpp
    engines/feq/fqshrunt.cpp
    engines/feq/ftlookup.cpp
    engines/feq/genscn.cpp
    engines/feq/getcode.cpp
    engines/feq/getsvn_msw_lf95.cpp
    engines/feq/hecdmy.cpp
    engines/feq/hi_iq_ns.cpp
    engines/feq/home_name.cpp
    engines/feq/input.cpp
    engines/feq/inputuf.cpp
    engines/feq/iounits.cpp
    engines/feq/lf95_ms_s_npf.cpp
    engines/feq/linuxcr.cpp
    engines/feq/locsubs.cpp
    engines/feq/macro.cpp
    engines/feq/makpat.cpp
    engines/feq/miscfeq.cpp
    engines/feq/mkdir_fun.cpp
    engines/feq/newlookup.cpp
    engines/feq/ntmatrix.cpp
    engines/feq/ntwmxstr.cpp
    engines/feq/nxttok.cpp
    engines/feq/output.cpp
    engines/feq/putpat.cpp
    engines/feq/pwd_msw_lf95.cpp
    engines/feq/runinit.cpp
    engines/feq/schematic.cpp
    engines/feq/select.cpp
    engines/feq/sideweir.cpp
    engines/feq/svn_report.cpp
    engines/feq/tableid.cpp
    engines/feq/tdtchk_free.cpp
    engines/feq/timeman.cpp
)
