set(FEQ_FEQUTL_SOURCES
    engines/fequtl/binsearch.cpp
    engines/fequtl/bridge.cpp
    engines/fequtl/chanrat.cpp
    engines/fequtl/common.cpp
    engines/fequtl/conduit.cpp
    engines/fequtl/critq.cpp
    engines/fequtl/culverta.cpp
    engines/fequtl/culvertb.cpp
    engines/fequtl/culvertc.cpp
    engines/fequtl/culvertd.cpp
    engines/fequtl/culverte.cpp
    engines/fequtl/dynamic_storage.cpp
    engines/fequtl/embank.cpp
    engines/fequtl/expcon.cpp
    engines/fequtl/fequtl.cpp
    engines/fequtl/findbrk.cpp
    engines/fequtl/floodway.cpp
    engines/fequtl/fqshrftb.cpp
    engines/fequtl/fqshrinl.cpp
    engines/fequtl/fqshrlin.cpp
    engines/fequtl/fqshrplg.cpp
    engines/fequtl/fqshrstr.cpp
    engines/fequtl/fqshrtdl.cpp
    engines/fequtl/fqshrtim.cpp
    engines/fequtl/fqshrunt.cpp
    engines/fequtl/getsvn_msw_lf95.cpp
    engines/fequtl/hec2x.cpp
    engines/fequtl/home_name.cpp
    engines/fequtl/imptrap.cpp
    engines/fequtl/inputproc.cpp
    engines/fequtl/inv_gate.cpp
    engines/fequtl/lf95_ms_s_npf.cpp
    engines/fequtl/linuxcr.cpp
    engines/fequtl/location.cpp
    engines/fequtl/lprfit.cpp
    engines/fequtl/makelakexs.cpp
    engines/fequtl/mkembank.cpp
    engines/fequtl/mkwspro.cpp
    engines/fequtl/newlookup.cpp
    engines/fequtl/numrmath.cpp
    engines/fequtl/nxttok.cpp
    engines/fequtl/orifice.cpp
    engines/fequtl/pumpitem.cpp
    engines/fequtl/pwd.cpp
    engines/fequtl/riserclv.cpp
    engines/fequtl/ritter.cpp
    engines/fequtl/rootfind.cpp
    engines/fequtl/sinuous.cpp
    engines/fequtl/sortser.cpp
    engines/fequtl/svn_report.cpp
    engines/fequtl/tabfit.cpp
    engines/fequtl/tableid.cpp
    engines/fequtl/tablook.cpp
    engines/fequtl/tabstore.cpp
    engines/fequtl/tracking.cpp
    engines/fequtl/ufgate.cpp
    engines/fequtl/ufgculv.cpp
    engines/fequtl/wspro.cpp
    engines/fequtl/xsection.cpp
)
