set(FEQ_RUNTIME_SOURCES
    engines/runtime/backspac.cpp
    engines/runtime/close.cpp
    engines/runtime/ctype.cpp
    engines/runtime/d_lg10.cpp
    engines/runtime/d_mod.cpp
    engines/runtime/d_sign.cpp
    engines/runtime/dolio.cpp
    engines/runtime/due.cpp
    engines/runtime/endfile.cpp
    engines/runtime/err.cpp
    engines/runtime/exit_.cpp
    engines/runtime/f77_aloc.cpp
    engines/runtime/feq_compat.cpp
    engines/runtime/fmt.cpp
    engines/runtime/fmtlib.cpp
    engines/runtime/getarg_.cpp
    engines/runtime/i_dnnt.cpp
    engines/runtime/i_indx.cpp
    engines/runtime/i_len.cpp
    engines/runtime/i_nint.cpp
    engines/runtime/i_sign.cpp
    engines/runtime/iargc_.cpp
    engines/runtime/iio.cpp
    engines/runtime/ilnw.cpp
    engines/runtime/inquire.cpp
    engines/runtime/lread.cpp
    engines/runtime/lwrite.cpp
    engines/runtime/open.cpp
    engines/runtime/pow_dd.cpp
    engines/runtime/r_lg10.cpp
    engines/runtime/r_sign.cpp
    engines/runtime/rdfmt.cpp
    engines/runtime/rewind.cpp
    engines/runtime/rsfe.cpp
    engines/runtime/rsli.cpp
    engines/runtime/rsne.cpp
    engines/runtime/s_cat.cpp
    engines/runtime/s_cmp.cpp
    engines/runtime/s_copy.cpp
    engines/runtime/s_stop.cpp
    engines/runtime/sfe.cpp
    engines/runtime/sig_die.cpp
    engines/runtime/sue.cpp
    engines/runtime/typesize.cpp
    engines/runtime/uio.cpp
    engines/runtime/util.cpp
    engines/runtime/wref.cpp
    engines/runtime/wrtfmt.cpp
    engines/runtime/wsfe.cpp
    engines/runtime/wsle.cpp
    engines/runtime/wsne.cpp
    engines/runtime/xwsne.cpp
)
