#include <feq/approach_residual.hpp>
#include <feq/root_solver.hpp>
#include <feq/steady_residual.hpp>
#include <feq/culvert_loss.hpp>
#include <feq/section_energy.hpp>
#include <feq/conduit_boundary.hpp>
// Public headers must coexist in one client translation unit.
// Work: Astra. Sponsor: Rainstar. Foundation: Hashem. MIT licensed.
#include <feq/arch_perimeter.hpp>
#include <feq/decimal.hpp>
#include <feq/elevation_arguments.hpp>
#include <feq/md5.hpp>
#include <feq/power.hpp>
#include <feq/power_spacing.hpp>
#include <feq/profile_matrix.hpp>
#include <feq/section_flux.hpp>
#include <feq/section_geometry.hpp>
#include <feq/section_interpolation.hpp>
#include <feq/section_extension.hpp>
#include <feq/gaussian_rule.hpp>
#include <feq/section_sinuosity.hpp>
#include <feq/gate_residual.hpp>
#include <feq/section_properties.hpp>
#include <feq/storage.hpp>
#include <feq/table_interpolation.hpp>
#include <feq/trigonometry.hpp>
#include <feq/weir_flow.hpp>
#include <feq/full_barrel.hpp>
#include <feq/tailwater_residual.hpp>
#include <feq/channel_rating.hpp>
