#!/usr/bin/env python3
"""Generate C++ constants from the independently extracted original tables."""
import json
from pathlib import Path

root = Path(__file__).resolve().parents[1]
source = json.loads((root / 'recovery/runup-1991-tables.json').read_text())
arrays = {a['name']: a['values'] for a in source['arrays']}
arrays['DLL'] = sum((arrays.pop(f'DL{i}') for i in range(1, 5)), [])
lines = ['// Generated by tools/generate_runup_tables.py; do not edit.',
         '// Original FEMA RUNUP numerical data. See NOTICE.md.',
         '#pragma once', '#include <array>', '#include <cstdint>',
         'namespace legacy::runup::detail::tables {']
for name, values in arrays.items():
    lines.append(f'inline constexpr std::array<std::int32_t, {len(values)}> {name}{{{{')
    for start in range(0, len(values), 13):
        lines.append('    ' + ', '.join(map(str, values[start:start + 13])) + ',')
    lines.append('}};')
lines.append('} // namespace legacy::runup::detail::tables')
(root / 'src/runup/tables.hpp').write_text('\n'.join(lines) + '\n')
